development:
  adapter: mysql
  encoding: unicode
  database: roomorama_boxen
  pool: 5
  host: localhost
  port: 3306
  username: root
  password:

test:
  adapter: mysql
  encoding: unicode
  database: roomorama_boxen_test
  pool: 5
  host: localhost
  port: 3306
  username: root
  password:

production:
  development
